### PR TITLE
Fix wrapping method to support multiple print-width characters

### LINKED ISSUE #787: Wrapping characters spanning multiple print-width
Currently, wrapping will not work as expected if there are characters spanning multiple print-width in a line.

Screenshot from 2019-12-24 15-42-49

I haven't investigated the code, but I think that probably the print-width of a character is always assumed to be `1` in `bat`. In this case it can be fixed by properly calculating the print-width with some crates e.g. `unicode-width`.

### PR DESCRIPTION
**Pull request by Kogia-sima**
Fix #787 and #811

### CODE REVIEW

**Comment by eth-p** [comment]
Awesome work, thanks for implementing this!

**Comment by sharkdp** [comment]
@Kogia-sima Thank you very much for your contribution!

Sorry for being pedantic about this, but what is the content of the text that you added as (unit) tests? I'd appreciate if that would be something that is (1) "neutral" in terms of content and (2) uncritical with respect to licensing.

Maybe it would be best to use some very stupid meaningless dummy text, possibly repeating one and the same word (i.e. without reusing any existing text).

**Comment by Kogia-sima** [comment]
Those texts are cited from [here](http://zarniwhoop.uk/files/PDF-languages/HOTO-Write-Multilingual-Text.pdf).

I don't know whether those texts are suitable for MIT/Apache-2.0 license, but it might include affiliated contents. Anyway, I've replaced the input data with the texts which does not reuse any existing sentence.

**Comment by sharkdp** [comment]
@Kogia-sima Thank you for the update and thank you for implementing this!

**Comment by sharkdp** [comment]
This has been released in [bat 0.13](https://github.com/sharkdp/bat/releases/tag/v0.13.0).

**Pull request merged**
