### PR TITLE
Update sublimehq/Packages to master

### LINKED ISSUE #443: .sc files should be treated as scala files
These are either [scala worksheet](https://github.com/scala-ide/scala-worksheet/wiki/Getting-Started) files or [ammonite script files](https://ammonite.io/#import$file) 

>Scala worksheets are normal Scala files, except that theythey end in .sc instead of .scala.

(and when I say treated I specifically mean syntax highlighted; not sure if anything else changes based on the file type)

### LINKED ISSUE #499: Can not update sublimehq/Packages to the latest state
When updating the `assets/syntaxes/Packages` submodule to the latest state, calling `assets/create.sh` fails with:

```
[..] assets/syntaxes/Packages/Go/Go.sublime-syntax: Invalid YAML file syntax
```

This is probably an upstream problem (either in sublimehq/Packages or syntect). Any help is greatly appreciated.

### PR DESCRIPTION
**Pull request by benwaffle**
Fixes #499 
Fixes #443

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you very much for looking into this. Great that we can now actually upgrade the submodule to the latest state without getting any errors. Unfortunately, things are not that simple.

The `syntect` crate comes with an example program called "syntest". It runs syntax definition tests that come with some of the Sublime text syntaxes. With the old version of sublimehq/Packages (the one `syntect` currently points to), there are only a few failures (the first number in each line is the number of failed tests):
```
> cargo run -q --example syntest | rg Failed    
Ok(FailedAssertions(38, 43))
Ok(FailedAssertions(1, 639))
Ok(FailedAssertions(6, 612))
```

After updating to the lastest version of sublimehq/Packages, there are quite a few more:
```
> # edit the yaml-rust dependency in `Cargo.toml` to point at version 0.4.3
> git submodule update --recursive --remote
> make packs
> cargo run -q --example syntest | rg Failed             
Ok(FailedAssertions(1, 6297))
Ok(FailedAssertions(17, 3487))
Ok(FailedAssertions(3, 1055))
Ok(FailedAssertions(817, 6814))
Ok(FailedAssertions(6, 165))
Ok(FailedAssertions(1, 935))
Ok(FailedAssertions(6, 739))
Ok(FailedAssertions(61, 6695))
Ok(FailedAssertions(29, 6138))
Ok(FailedAssertions(15, 2886))
```

Having more test failures isn't *necessarily* a sign that things got worse (it could just be more tests), but I'm afraid it might very well be.

I think this is also the reason why https://github.com/trishume/syntect/pull/246 has not been merged. 

(also, after updating the `yaml-rust` dependency, there are three failing unit tests: `html::tests::tokens`, `html::tests::strings`, `parsing::parser::tests::can_parse_includes`)

/cc @keith-hall: FYI

**Comment by benwaffle** [comment]
If i run `make update-known-failures` in syntest, then update sublime text Packages, then run `make syntest`, it passes. This way doesn't show any more failures than before the update.

**Comment by keith-hall** [comment]
some of the failing syntax test assertions are false positives due to syntect behaving differently than Sublime wrt how it handles assertions which span the end of the line, and would be fixed by https://github.com/trishume/syntect/pull/185. I've just seen I need to fix some conflicts on that PR.
As to whether the quality of the highlighting will suffer more with those newer definitions and syntect's incorrect `embed`/`escape` handling compared to the older definitions, I couldn't really say... I guess it is subjective based on the input and the color schemes etc. IIRC it mainly affects files with JavaDoc comments and PHP embedded in Markdown code fences.

**Comment by sharkdp** [comment]
Thank you both for the information!

I was about to say "let's give this a try" when I ran `bat test.*` on a folder of test inputs I collected over the last year and saw that `bat` now panics on simple JSON files (modified example to make it smaller):
``` json
{
  "a": {
    "b": 1
  }
}
```

```
> bat test.json
▶ RUST_BACKTRACE=1 bat test.json
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::panicking::panic
             at src/libcore/panicking.rs:49
  11: <syntect::highlighting::highlighter::HighlightIterator as core::iter::traits::iterator::Iterator>::next
  12: <syntect::highlighting::highlighter::HighlightIterator as core::iter::traits::iterator::Iterator>::next
  13: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  14: syntect::easy::HighlightLines::highlight
  15: <bat::printer::InteractivePrinter as bat::printer::Printer>::print_line
  16: bat::controller::Controller::run
  17: bat::main
  18: std::rt::lang_start::{{closure}}
  19: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  20: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  21: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  22: std::panicking::try
             at src/libstd/panicking.rs:275
  23: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  24: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  25: main
  26: __libc_start_main
  27: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
───────┬───────────────────────────────────────────────────────
       │ File: test.json
───────┼───────────────────────────────────────────────────────
   1   │ {
   2   │   "a": {
   3   │     "b": 1
   4   │   }
```

**Comment by keith-hall** [comment]
That is interesting, and definitely worth looking into - thanks for the minimal test case @sharkdp. I can't promise when I will find time to do so, however, so if someone else gets chance to investigate, please do! I wonder if it is related to the yaml-rust dependency, or the syntax definition changes. (presumably the latter but it would be nice to isolate to confirm)

I believe the syntect unit test failures are just because they are brittle tests relying on some of the syntaxes from the sublimehq packages and color schemes which are also submodules and occasionally updated. Any change is likely to break the tests unfortunately.

**Comment by keith-hall** [comment]
I can confirm that `syntect`s `syncat` example suffers from the same problem with JSON files, and it seems to be https://github.com/sublimehq/Packages/pull/862 which triggers it, as it works with the previous commit. This will need to be fixed upstream in `syntect`.

**Comment by sharkdp** [comment]
A new version of syntect has been released (https://github.com/trishume/syntect/pull/259#issuecomment-533919892) which includes the fix by @keith-hall.

@benwaffle If possible, could you please update the PR and have bat depend on the latest version of syntect?

**Comment by sharkdp** [comment]
Nevermind, the update was already done in #671. I rebased your branch onto `master`.

**Comment by sharkdp** [comment]
I tested this on my (small) collection of files and couldn't see any obvious regression. I think we should give this a try.

**Comment by sharkdp** [comment]
@benwaffle @keith-hall Thank you!

**Comment by sharkdp** [comment]
This has been released in [bat 0.13](https://github.com/sharkdp/bat/releases/tag/v0.13.0).

**Pull request merged**
