### PR TITLE
Add support for ruby-slim syntax

### LINKED ISSUE #1693: add ruby slim-lang syntax support
**Syntax:**
Ruby's slim templating language (`*.slim`)

**Guideline Criteria:**
https://packagecontrol.io/packages/Ruby%20Slim (67K downloads on packagecontrol.io)
https://github.com/slim-template/ruby-slim.tmbundle

### PR DESCRIPTION
**Pull request by mfinelli**
Resolves #1693

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you for your contribution. Could you please rebase this PR and move the CHANGELOG line to the "unreleased" section? It got moved down when I released a new bat version recently.

**Comment by keith-hall** [comment]
This submodule is missing a sublime-syntax file. Please follow the instructions to add one by converting the tmLanguage file, while leaving the submodule intact. https://github.com/sharkdp/bat/blob/master/doc/assets.md#adding-new-builtin-languages-for-syntax-highlighting

**Comment by mfinelli** [comment]
@keith-hall thanks, I've generated the slim-syntax as in the guide with a test plus rebased onto the latest master

**Review by keith-hall — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
