### PR TITLE
Simplify comments in bug_report issue template

### PR DESCRIPTION
**Pull request by xerus2000**
Adjusted as requested in #1374 :)

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you for your contribution. To be honest, I'm not really sure it improves the template. I'd love to hear @eth-p's opinion. Also, note that this template might change if we decide to implement #1405.

**Comment by xerus2000** [comment]
One of the important things is the use of comments, because without them users have to replace text in the template, which is tedious. Everything else are basically little wording inconsistencies.

**Comment by eth-p** [comment]
I could go either way. Both the current template and these changes would work for the template.

As for my opinion on the changes:

- They're more concise.
- The wording is more formal.

My only issue would be with replacing the part about Linux/MacOS with "Unix-like". I haven't tested the diagnostics script outside of MacOS or Linux, and I'm not confident it will work on other platforms like BSD.

**Comment by xerus2000** [comment]
Fair, changed it back :)

**Comment by sharkdp** [comment]
Thank you for the updates. I took your changes and added a few improvements (I hope) on top.

**Comment by xerus2000** [comment]
I don't see how lots of empty lines are improvements, but hey - your call ;)

**Pull request merged**
