### PR TITLE
added elvish syntax

### PR DESCRIPTION
**Pull request by rsteube**
added syntax for [Elvish Shell](https://elv.sh/)

Listed as sublime language support here: https://github.com/elves/awesome-elvish

### CODE REVIEW

**Comment by sharkdp** [comment]
Welcome and thank you for your PR.

Have you seen the "syntax request" issue type (https://github.com/sharkdp/bat/issues/new?assignees=&labels=syntax-request&template=syntax_request.md&title=) and, in particular, the guideline for adding new syntaxes?

Also, note that there is an easy way to customize your version of bat: https://github.com/sharkdp/bat#adding-new-syntaxes--language-definitions

**Comment by rsteube** [comment]
ah, no didn't see that part with the 10.000 downloads - 31 is pretty far from that XD
i got it working locally, just thought it might be useful for others as well

**Comment by data-man** [comment]
@sharkdp 
> please make sure that it meets our
guidelines for adding new syntaxes:
> 10,000 downloads on packagecontrol.io

But why? :(
I want to make PR for Zig language, but [Zig Language](https://packagecontrol.io/packages/Zig%20Language) package has 1K downloads only.
Please, can you relax this requirement?

**Comment by sharkdp** [comment]
Have you seen that it's possible to customize `bat`? https://github.com/sharkdp/bat#adding-new-syntaxes--language-definitions

**Comment by data-man** [comment]
Sure, but Zig's support in the official build is preferable. :)

**Comment by rsteube** [comment]
Yes is easy enough to customize, would by nice though to have a single command solution to add these or a system-wide config-dir to add these using the system package-manager (e.g. bat-syntax-zig).

**Comment by sharkdp** [comment]
@data-man: If you like, you could open a new ticket to discuss the 10k downloads policy. I'm pretty sure it's not ideal, but I wanted to have *something* to limit the amount of syntaxes that we need to maintain. `bat` startup speed is also a big concern.

@rsteube excellent points. Maybe we could also list them in that new ticket where others can also see them.

**Pull request closed without merging**
