### PR TITLE
Scope environment variable and commands sections in Manpages

### LINKED ISSUE #2459: man: Commands aren't highlighted at all
**What steps will reproduce the bug?**

I'm using `bat`as a man pager:

```console
$ echo $MANPAGER
bat-for-man

$ cat $(which bat-for-man )
#!/bin/sh
#
# man(1) can use a custom pager, but will exec `MANPAGER` as-is (e.g.: it won't
# pass it to a shell) so using arguments isn't possible.

col -bx < "$1" | bat --language man -p
```

**What happens?**

On man pages listing commands, commands themselves are not highlighted.

I'll use `sway(5)` as an example. With `bat`:

image

**What did you expect to happen instead?**

Without `bat`:

image

**How did you install `bat`?**

Distribution packages (Alpine)

**bat version and environment**

#### Software version

bat 0.22.1

#### Operating system

Linux 6.1.8-0-edge

#### Command-line

```bash
bat --diagnostic 
```

#### Environment variables

```bash
SHELL=/bin/zsh
PAGER='bat -p'
LESS='-RX --mouse --quit-if-one-screen'
LANG=en_GB.UTF-8
LC_ALL=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=/home/hugo/.config
XDG_CACHE_HOME=/home/hugo/.cache
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER=bat-for-man
```

#### System Config file

Could not read contents of '/etc/bat/config': No such file or directory (os error 2).

#### Config file

Could not read contents of '/home/hugo/.config/bat/config': No such file or directory (os error 2).

#### Custom assets metadata

Could not read contents of '/home/hugo/.cache/bat/metadata.yaml': No such file or directory (os error 2).

#### Custom assets

'/home/hugo/.cache/bat' not found

#### Compile time information

- Profile: release
- Target triple: x86_64-alpine-linux-musl
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-alpine-linux-musl

#### Less version

```
> less --version 
less 608 (POSIX regular expressions)
Copyright (C) 1984-2022  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

### PR DESCRIPTION
**Pull request by keith-hall**
Fixes #2459

### CODE REVIEW

**Review by sharkdp — APPROVED** [review]
Thank you!

**Comment by Enselic** [comment]
Let's merge!

**Comment by WhyNotHugo** [comment]
Thanks!

**Comment by WhyNotHugo** [comment]
There seem to be some cases where this isn't worked properly:

image

image

image

It's not immediately obvious to me exactly what is wrong.

**Pull request merged**
