### PR TITLE
Added fish shell completions.

### PR DESCRIPTION
**Pull request by eth-p**
Added some completions for fish shell.

### CODE REVIEW

**Comment by sharkdp** [comment]
Thanks!

There is a way to auto-generate completion files for bash, zsh, fish and PowerShell via `clap` (see for example: https://github.com/sharkdp/fd/pull/66/files, https://github.com/sharkdp/fd/blob/master/build.rs) which I would prefer in order tp prevent maintenance overhead.

What do you think?

**Comment by eth-p** [comment]
That's a pretty cool feature! Automatically generating completion files would definitely be the way to go.

**Comment by sharkdp** [comment]
I hope it's okay if I close this PR. I have opened #115 to track the addition of auto-generated completion files.

Thank you very much for your contribution.

**Comment by sboukortt** [comment]
Unfortunately, the generated fish completion does not complete filenames, and so pressing Tab does nothing for them. That’s sufficiently annoying that I simply deleted the completion file on my machine.

**Comment by sharkdp** [comment]
@sboukortt Oh :frowning_face:. Could you please open a new ticket to address this?

**Comment by sboukortt** [comment]
Done (#372), thanks for the suggestion.

**Pull request closed without merging**
