### PR TITLE
"No newline at end of file" warning

### PR DESCRIPTION
**Pull request by obfusk**
I created this draft PR (which currently implements a very crude -- and possibly incomplete -- "fix") in the hope that it can serve as a place to identify which code is impacted by and discuss specific ways of solving #975.

### CODE REVIEW

**Comment by eth-p** [comment]
A couple things should be changed:

- It needs to be configurable with an option (`clap_app.rs`)
    Ideally, this should be added like the style components with `--warning=no-ending-newline`. If you want an easy way to implement this for now though, you can copy parts of the `--wrap` flag to just have a simple enum instead.

- I think the warning should show up after the file contents, instead of above the header.

- You might want to integrate it into the printer a little bit better. You can use `create_fake_panel("<!>")` to create a sidebar that shows "<!>" instead of the line number, and print the warning after that. Coloring the warning sign might require a bit more work, though.

- The solution to figuring out that there isn't a final newline is clever, but it's not immediately obvious that only the last line might not have a `\n` character in it. Is there any chance that you could add a comment that explains that?

**Comment by obfusk** [comment]
Thanks for the feedback!

> 1. It needs to be configurable with an option (`clap_app.rs`)

I absolutely agree. Hence "crude" and "draft" :) I was planning on looking into that when it's clear what the extent of the configurability should be and adding it to the PR.

> 2. You might want to integrate it into the printer a little bit better. You can use `create_fake_panel("/!\")` to create a sidebar that shows `/!\` instead of the line number, and print the warning after that. Coloring the warning sign might require a bit more work, though.

I had not looked into the possibilities for that yet. Thanks for the suggestion. I was also waiting on more feedback on how people want the warning to look before spending significant time on that. I would also assume it doesn't work w/ `--plain`?

> 3. The solution to figuring out that there isn't a final newline is clever, but it's not immediately obvious that only the last line might not have a `\n` character in it. Is there any chance that you could add a comment that explains that?

Good idea. I'll add that to the PR.

I'm also not entirely sure this is the correct place to detect and print the error. It might be better (though more complicated) to detect this at a higher level or pass the "error" up and process it there. Should this be considered a feature/bug of this printer or of `bat` as a whole?

> 4. ~I think the warning should show up after the file contents, instead of above the header.~
> This is a consequence of intertwining `eprintln!` and `write!`, and it actually results in inconsistent behavior (and doesn't work with the pager).
> One possible solution is to use point (2) above and just write it to the writer instead of using `eprintln!`.

I'm not entirely sure why the `eprintln!` shows up before the `write!`. Normally, when outputting to a terminal (and not using a pager), I'd expect `stdout` and `stderr` to be line-buffered and for lines printed to `stderr` and `stdout` to show up in the correct order. I did not yet investigate why this doesn't happen with the output abstraction `bat` uses.

I explicitly chose to output the warning to `stderr` because that way it doesn't show up in the actual output but is still shown to the user. It is common to print errors and warnings to `stderr` instead of to `stdout`. Whether this is the correct choice in this case, I'm not sure. I'd like to hear what others think. At the very least the current PR should be fixed so that the error is printed at the end instead of before the last line.

I see (at least) these options:

1. print an error to `stderr` for each file after writing the complete file, or maybe after writing all files.
2. use an extra line + sidebar to add the warning "in-place" (what to do with `--plain` then?)
3. append a warning symbol to the end of the line (might be hard to understand and might make wrapping more complex though)

Or maybe allow the user to select one of (some of) these options.

**Comment by eth-p** [comment]
> I explicitly chose to output the warning to stderr because that way it doesn't show up in the actual output but is still shown to the user. It is common to print errors and warnings to stderr instead of to stdout. Whether this is the correct choice in this case, I'm not sure. I'd like to hear what others think. At the very least the current PR should be fixed so that the error is printed at the end instead of before the last line.

This is a really complex situation, sadly. While I definitely agree about using `stderr` for its intended purpose, we have a few scenarios to consider:

1. **Printing to the terminal with pager.**
    We can't feed `stderr` into the printer, so all error output has to either be printed before starting the pager so they doesn't interfere with eachother, or mixed into `stdout` so the pager can read it too.

2. **Printing to the terminal without the pager.**
    As long as the inconsistent behavior can be fixed, `stderr` is preferable.

3. **Printing to a pipe.**
    For this case, it should print to `stderr` so the warning isn't mixed into the piped output.

> I had not looked into the possibilities for that yet. Thanks for the suggestion. I was also waiting on more feedback on how people want the warning to look before spending significant time on that. I would also assume it doesn't work w/ --plain?

Correct. If the `numbers` style is missing, it wouldn't be visible. One possible solution would be to take a hybrid approach where it prints `[bat warning]: FILE.EXT is missing an ending newline` when the inline warning wouldn't be possible.

> I'm also not entirely sure this is the correct place to detect and print the error. It might be better (though more complicated) to detect this at a higher level or pass the "error" up and process it there. Should this be considered a feature/bug of this printer or of bat as a whole?

Considering this might be undesired behavior for `bat`-as-a-library, I'm would consider it to be more of a `bat` application feature rather than a printer feature. Passing the warning up would be a good idea, but it would also complicate things if we wanted to print inline warnings. @sharkdp, thoughts?

**Comment by sharkdp** [comment]
I haven't followed the discussion above in details, but my thoughts:
* If we are writing to a pipe, don't do anything about the missing EOL. We want to behave like `cat`.
* I'm not so sure about the `--warn=a,b,c` thing. It would consistent with other `bat` options, but with tickets like #1032 open, I'm not so sure if we should go the same way with this. Especially since we don't have any other options right now. Maybe a simple `--no-missing-eol-warning` would also be fine.
* In `--plain` mode, I wouldn't show any warnings either. `--plain` implies a few other things already. Maybe it should also imply `--no-missing-eol-warning` (or however we decide to call it).
* In non-plain mode, I would print the warning to *STDOUT*. STDERR is for `bat` errors/warnings. If `bat` was not able to perform it's intended action. But here, everything goes according to plan. We print the full file contents. We only want to warn the user of the missing EOL at the EOF.

**Comment by sharkdp** [comment]
Closing for now to clean up the list of open PRs.

**Pull request closed without merging**
