### PR TITLE
Add SaltStack SLS syntax

### PR DESCRIPTION
**Pull request by Martin819**
Adding new syntax highlighting for SaltStack states - SLS files.

Example:
Screenshot from 2019-09-09 15-27-47

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you for your contribution.

I've never heard of SaltStack before. It sounds like this syntax would be something very specific. Have you considered [adding this syntax to your local installation](https://github.com/sharkdp/bat#adding-new-syntaxes--language-definitions)?

**Comment by Martin819** [comment]
Hi @sharkdp, I already have it my local installation and it works just fine and that's why I felt it would be great if bat would include it by default.
SaltStack is an open-source configuration management software, very similar to Ansible. It uses SLS files which are in fact conbination of YAML and Jinja2. The problem is that either YAML nor Jinja2 syntax highlighting works for these files. That's why SaltStack itself came with this syntax highlight which wraps aroung Jinja2 highlight and enables it to be used on YAML+Jinja2 files.

**Comment by sharkdp** [comment]
@eth-p Your opinion?

Maybe we should add some policy to make objective decisions on similar PRs that add new syntaxes.

SublimeText package is here:
https://packagecontrol.io/packages/SaltStack-related%20syntax%20highlighting%20and%20snippets

**Comment by eth-p** [comment]
@sharkdp We should definitely make some kind of objective policy for adding new syntaxes. The hard part is going to be figuring out how to gather metrics on the proposed language, though.

While SublimeText is a decent way of figuring out how many people use both Sublime and the language, I feel like it could be missing out on a potentially significant portion of users who don't actually use Sublime.

Some other metrics we could use:

- StackOverflow (survey, tag count, etc.)
- Atom plugins (download count)
- JetBrains language plugins (download count)

Additionally, what do you think would be a good "minimum" number of downloads for a language to be considered popular enough that it should be added?

**Comment by sharkdp** [comment]
> Some other metrics we could use: [...]

That's certainly a good idea!

> Additionally, what do you think would be a good "minimum" number of downloads for a language to be considered popular enough that it should be added?

So far, my threshold was somewhere between 10k and 20k total downloads. But I guess I wasn't strictly following that.

**Comment by eminence** [comment]
Another possibility might be to use the list of languages that github itself will syntax highlight:  https://github.com/github/linguist/blob/master/vendor/README.md

**Comment by Martin819** [comment]
Hi, regarding the questions on the need for this language, there are some results:

- over 2000 questions with tags "salt-stack" or "salt" --> [LINK](https://stackoverflow.com/questions/tagged/salt-stack+or+salt)

- Atom plugin available --> [LINK](https://atom.io/packages/language-salt)

- Not available for Jetbrains, but that's not a surprise since Salt is a cloud management service, you edit the files in 99% cases in CLI and not in the UI based IDEs.

- GitHub syntax is available --> [LINK(from README file from previous post)](https://github.com/saltstack/atom-salt)

**Comment by sharkdp** [comment]
@Martin819 Thank you for the detailed update! Let's merge this for now.

If we have a problem with too many syntax being bundled with `bat` in the future, I guess it's not too bad to remove some of them again - even though it is a regression of some sort.

**Comment by sharkdp** [comment]
(nightly builds are currently broken, but this has nothing to do with this PR)

**Comment by sharkdp** [comment]
This has been released in [bat 0.13](https://github.com/sharkdp/bat/releases/tag/v0.13.0).

**Pull request merged**
