### PR TITLE
Add new file_extensions for INI

### PR DESCRIPTION
**Pull request by Freed-Wu**
<https://coverage.readthedocs.io/en/6.3.2/>

### CODE REVIEW

**Comment by keith-hall** [comment]
Please also update https://github.com/sharkdp/bat/blob/master/doc/assets.md#manual-modifications

**Comment by Freed-Wu** [comment]
> Please also update https://github.com/sharkdp/bat/blob/master/doc/assets.md#manual-modifications

Fixed

**Review by sharkdp — APPROVED** [review]

**Comment by sharkdp** [comment]
Thank you. Can you please fix the merge conflicts?

**Comment by Freed-Wu** [comment]
Fixed.

**Pull request merged**
