### PR TITLE
CICD: Make the 'cargo fmt' check a toplevel job

### PR DESCRIPTION
**Pull request by Enselic**
Mainly to make it easier to see what went wrong when CI fails.

If this ever gets of out sync with a particular Rust version, we can most likely
save the situation by introducing a `rustfmt.toml` file.

Note that I choose to make the config minimal (e.g. without `name`). I think it does not make things harder to understand. In fact, I think it makes things easier to understand and maintain. I also use the default Rust installation instead of installing our own. That's just unnecessary to do in this case.

### CODE REVIEW

**Comment by sharkdp** [comment]
> Note that I choose to make the config minimal (e.g. without `name`).

You mean.. without a `Install rust toolchain` task?

**Comment by Enselic** [comment]
Yep. Rust stable is installed by default: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#rust-tools

**Comment by sharkdp** [comment]
To be honest, I'd rather spend a bit more time in CI than to have a *third* (undocumented and uncontrolled) Rust Version around.

**Comment by Enselic** [comment]
Ok, will add a step for that shortly :+1:

**Review by sharkdp — APPROVED** [review]
Thank you for the update.

**Pull request merged**
