### PR TITLE
add CFML syntax

### PR DESCRIPTION
**Pull request by brenton-at-pieces**

### CODE REVIEW

**Comment by brenton-at-pieces** [comment]
First attempt at adding a syntax to bat, may need tweaks, etc.

**Comment by keith-hall** [comment]
I don't see a syntax request issue for this, but https://packagecontrol.io/packages/CFML shows that it meets our requirements and the test file looks good, so I approve 🙂

**Review by keith-hall — APPROVED** [review]

**Comment by brenton-at-pieces** [comment]
Fixed conflict in CHANGELOG.md

**Comment by keith-hall** [comment]
Currently CI is failing due to https://github.com/sharkdp/bat/issues/3043

**Pull request merged**
