### PR TITLE
Add simple configuration file

### PR DESCRIPTION
**Pull request by sharkdp**
This allows users to create simple configuration file (`~/.config/bat/config` on Linux) that has the following format:

```bash
--flag1
--flag2
--option1=value1
# lines beginning with '#' are ignored
--option2 value2
# empty lines and trailing whitespace are also ignored

--option3=value3
# Flags and options can also be on a single ine:
--flag4 --flag5 --option4 value4
```

It also adds support for `BAT_OPTS` environment variable with the same format. It takes precedence over the configuration file.

see #310

### CODE REVIEW

**Comment by sharkdp** [comment]
There are a few issues with this (apart from the failing tests :smile:)

To add `--theme="Sublime Snazzy"` to the configuration file, users would have to put either
```
--theme
Sublime Snazzy
```

or
```
--theme=Sublime Snazzy
```

into their configuration file. Both are confusing and the more sane alternatives do not work (`--theme="Sublime Snazzy"`) or (--theme "Sublime Snazzy").

**Comment by sharkdp** [comment]
The issue mentioned above is now resolved.

There is one thing missing: `--style` can not be passed in twice, so users will not be able to configure `--style` in their config file and overwrite it on the command-line later.

**Comment by SimenB** [comment]
Would it be possible to set an env variable pointing to the configuration file, similar to `ripgrep`'s `$RIPGREP_CONFIG_PATH`?

**Comment by sharkdp** [comment]
@SimenB Can you please open a new ticket to address this? Thank you

**Pull request merged**
