### PR TITLE
Add Coldark themes

### PR DESCRIPTION
**Pull request by ArmandPhilippot**
Added both versions of [Coldark](https://github.com/ArmandPhilippot/coldark).

I am not used to submodules. Hope I did it right. The linked repo contains two themes: the light version and the dark version.

There are some minor changes between the VS Code and bat versions since the tokens differ a bit. Is there a list of scopes somewhere? I searched but found nothing ... For example, how to color the keys in a json file?

### CODE REVIEW

**Comment by ArmandPhilippot** [comment]
Sorry, I didn't do the manipulations in "Development". I didn't think it was about adding a theme ... now that I see cargo failing, I imagine it came from there.

**Comment by keith-hall** [comment]
Thanks for your contribution. It looks like the test is failing because your new color schemes need to be added to the unit test:
https://github.com/sharkdp/bat/blob/2ffbe08eb171ef71ee08b4da38c87ffa75934f72/tests/assets.rs#L14

**Comment by ArmandPhilippot** [comment]
It seems that this is not enough, and even worse ...

I also tried to start from 0 by following the instructions in [Development](https://github.com/sharkdp/bat#development) but there are 2 git submodules that I cannot clone (`sublimehq/Packages` and `elixir-sublime-syntax`). I do not understand why.

If I ignore this problem, and use `bash assets/create.sh`, `.rej` files are created related to the Sublime packages.

```
--- syntaxes/01_Packages/C#/C#.sublime-syntax
+++ syntaxes/01_Packages/C#/C#.sublime-syntax
@@ -1312,7 +1312,7 @@ contexts:
             2: punctuation.separator.cs
             3: punctuation.section.brackets.end.cs
             4: keyword.operator.pointer.cs
-    - match: \((?=(?:[^,)(]*|\([^\)]*\))*,)
+    - match: \((?=(?:[^,)(]|\([^\)]*\))*,)
       scope: punctuation.section.group.begin.cs
       push:
         - meta_scope: meta.group.tuple.cs
```
And `cargo test` always fails (the same problem as the original). Even adding the themes to the file `tests/assets.rs`.

I don't know if the initial problem is with the submodules that don't want to clone or if I'm just doing it wrong. Sorry for the inconvenience, the procedure did not seem complicated to me before trying.

**Comment by ArmandPhilippot** [comment]
I don't understand why it doesn't work. Mainly, I don't understand why tests that worked the first time are failing now ...

This time, I had no submodules issues, no `.rej` files, everything was working fine. When I run `cargo test` locally, I have no errors. On the other hand, I did not add these two modified files `assets/syntaxes.bin` and `assets/themes.bin` as I did not see them in other pull requests.

Have I forgotten something? I did a push force. Should I have removed the fork and made a clean one again?

**Comment by sharkdp** [comment]
Thank you for your contribution and sorry about that.. the current progress is kind of confusing when adding new themes:

We have some CI tests that simply run `cargo test` on the current state of the repository. These will fail when you add a new theme to the unit test, because `assets/themes.bin` is not included in this PR (which means that these tests will not see the new theme).

We also have a special CI test ("Test with new syntaxes and themes") which runs `assets/create.sh` before running `cargo test`. This one will fail if you do *not* include the new theme in the unit test.

To resolve this, you will need to commit the new `themes.bin` along with the submodule addition.

**Comment by sharkdp** [comment]
I think there is a way to solve this for the future: We should only run the `all_themes_are_present` test in the "Test with new syntaxes and themes" pipeline. I guess we could somehow disable it by default and then specifically enable the test for that pipeline.

**Comment by ArmandPhilippot** [comment]
Thank you for these explanations. I had looked at the base16-256 pull request, I didn't notice `themes.bin` therefore, I preferred not to add it. I figured it would generate the next bat update.

I just added the `themes.bin` file.

It might be interesting to update the `README.md` either directly under "Development" or in a sub-section to specify the files to commit for future contributors?

Something like :

```
### Add new theme

Follow the first 4 steps of [Development](https://github.com/sharkdp/bat#development). Then add your theme in `assets/themes`. Also edit the `tests/assets.rs` file to add your theme to the list.

Now you can follow the 5th step of "Development". You may need to re-run `cargo test` to make sure there are no errors.

Finally, you must commit:
* your theme
* .gitsubmodules
* unit.rt
* themes.bin
```

What do you think?

**Comment by sharkdp** [comment]
> I just added the `themes.bin` file.

Sorry if I wasn't clear above. I already fixed the underlying problem on your branch, so committing `themes.bin` is *not* necessary anymore now.

> It might be interesting to update the `README.md` either directly under "Development" or in a sub-section to specify the files to commit for future contributors?

Yes, absolutely :+1:. See also: #1211. I think it should be in a separate file that we link to from the main README. Probably in `assets/README.md` as well.

**Comment by ArmandPhilippot** [comment]
Ah ok! I thought it was just a correction of the tests. I did not understand that the file was no longer needed.

I just read the issue. So, I updated the Changelog. And yes, a separate file would be clearer; the README begins to be a bit long.

**Comment by sharkdp** [comment]
Added in [bat v0.17](https://github.com/sharkdp/bat/releases/tag/v0.17.0).

**Pull request merged**
