### PR TITLE
Add support for JSX in javascript and typescript

### PR DESCRIPTION
**Pull request by tobenna**

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you very much.


How will this work?

Will this be used for every `.js` file? Will it overwrite the default JavaScript syntax?

If we add this, do we still need the TypeScript syntax?

**Comment by tobenna** [comment]
@sharkdp 

> Will this be used for every .js file? Will it overwrite the default JavaScript syntax?

I'm not sure how the language resolution works in syntect.
But since there's already have support for `.js`
we can take [this](https://github.com/sharkdp/bat/pull/279/files#diff-b161992fce76f3192aaf04b511d20ec7R6) out.

So that `.js` files use the default syntax.

> If we add this, do we still need the TypeScript syntax?

We'll still need the other TypeScript syntax this just adds highlighting for `.tsx`

**Comment by sharkdp** [comment]
Thank you for the clarification.

It seems like this is a more modern JavaScript syntax, right? So I guess we can also leave it in.

**Comment by tobenna** [comment]
I tested it locally and it seems to work fine with both of them in there.

**Pull request merged**
