### PR TITLE
Update battest.py

### PR DESCRIPTION
**Pull request by SarveshMD**
Add decorator test `@classmethod` and fixed spellings.

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you.

Please follow steps 5-7 here: https://github.com/sharkdp/bat/blob/master/doc/assets.md#syntax-tests in order to make the tests pass.

**Comment by SarveshMD** [comment]
I ran `tests/syntax-tests/update.sh` and I found that there were 148 new files created. Is this normal or there is some problem ?

**Comment by sharkdp** [comment]
Hm, looks like there is a problem. Maybe try clearing the cache (https://github.com/sharkdp/bat/blob/master/doc/assets.md#troubleshooting)?

**Comment by SarveshMD** [comment]
The same result even after running `bat cache --clear`. :(

**Comment by sharkdp** [comment]
Ok, don't worry. I updated the file for you.

**Review by sharkdp — APPROVED** [review]

**Comment by SarveshMD** [comment]
Thanks :)

**Pull request merged**
