### PR TITLE
More consistent scoping in commands section in Manpages

### PR DESCRIPTION
**Pull request by keith-hall**
More improvements for #2459 as a follow up to #2461

### CODE REVIEW

**Comment by sharkdp** [comment]
@WhyNotHugo FYI

**Review by sharkdp — COMMENTED** [review]
Thank you

**Comment by Enselic** [comment]
@sharkdp Did you mean to mark this as Approved? Your comment indicates it :)

**Comment by sharkdp** [comment]
Yes :-)

**Review by sharkdp — APPROVED** [review]

**Comment by Enselic** [comment]
Let's merge then :D

**Pull request merged**
