### PR TITLE
Add MATLAB syntax test file

### PR DESCRIPTION
**Pull request by senden9**
I used a modified version of the pygments test file here. As noted in the license file.  Syntax highlighting looks correct. I have checked the created highlighted file. We also have quite some syntax here that is tested with that test.

The modification I made was to use block comments like they are in the official matlab documentation under https://www.mathworks.com/help/matlab/matlab_prog/comments.html
> To comment out multiple lines of code, use the block comment operators, `%{` and `%}`. The `%{` and `%}` operators must appear alone on the lines that immediately precede and follow the block of help text. Do not include any other text on these lines.

cc sharkdp/bat#1213

### CODE REVIEW

**Comment by senden9** [comment]
I opened an issue in the pygments repo for that change. Cross reference: https://github.com/pygments/pygments/issues/1582

**Comment by senden9** [comment]
Also the syntax highlighting is not 100% correct currently. I opened an issue upstream for that. Cross reference: https://github.com/sublimehq/Packages/issues/2561

**Comment by sharkdp** [comment]
Thank you very much for your contribution and for the other (upstream) issues/PRs!

**Comment by senden9** [comment]
Hi @sharkdp !
is it possible that you add the label `hacktoberfest-accepted` to this PR, #1336, and/or #1338? As far as I see this repository has the `hacktoberfest` tag on it. But my PRs do not count anyway.

I get this message for that three pull requests:
> Ineligible Repository
> Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

If you don't want to add its of course also fine :D

**Comment by sharkdp** [comment]
> As far as I see this repository has the hacktoberfest tag on it. But my PRs do not count anyway.

hm... :-/

> is it possible that you add the label `hacktoberfest-accepted`

done.

**Comment by senden9** [comment]
Thanks :+1:

**Pull request merged**
