### PR TITLE
Implemented LLVM syntax highlighting as submodule

### PR DESCRIPTION
**Pull request by ioncodes**
See https://github.com/sharkdp/bat/issues/1777 and discussion in https://github.com/sharkdp/bat/pull/1778.

### CODE REVIEW

**Comment by keith-hall** [comment]
Looks good. Please can you update the changelog as described in https://github.com/sharkdp/bat/blob/master/CONTRIBUTING.md#add-an-entry-to-the-changelog ? :)

**Comment by ioncodes** [comment]
@keith-hall Done!

**Review by keith-hall — APPROVED** [review]

**Review by Enselic — APPROVED** [review]
Worked nicely when I tried it out :+1: 

Thanks!

**Comment by Enselic** [comment]
Closed #1777

**Pull request merged**
