### PR TITLE
Map containers `.conf` files to TOML syntax

### PR DESCRIPTION
**Pull request by cyqsimon**
See https://github.com/containers/image/tree/main/docs.

### CODE REVIEW

**Review by Enselic — APPROVED** [review]
Probably non-trivial to add tests since absolute paths are involved, so I'll just assume this works. No objections from me.

**Comment by cyqsimon** [comment]
> Probably non-trivial to add tests since absolute paths are involved, so I'll just assume this works. No objections from me.

Ideas for a testing infrastructure for this sort of thing:
- `chroot`? This will still require privileges.
- Test containers? This will add a lot of complexity, but it might be worth it if it's also useful in other integration testing.

**Comment by eth-p** [comment]
> `chroot`? This will still require privileges.

There's also [PRoot](https://proot-me.github.io/), which uses ptrace to emulate chroot. I don't believe there are any alternatives for MacOS or Windows, but it could work when running tests on Linux systems.

**Comment by Enselic** [comment]
Probably easier to set `XDG_CONFIG_HOME` in the test to some path that the test suite controls? (But again, not needed for merge as far as I'm concerned.)

**Comment by sharkdp** [comment]
I will merge it without the tests, if that's okay with everyone.

**Pull request merged**
