### PR TITLE
#2664: Pipeline should fail when tests fail on Windows/Powershell

### PR DESCRIPTION
**Pull request by boyvanduuren**

### CODE REVIEW

**Comment by boyvanduuren** [comment]
Hmm, that's failing exactly as I'd expect it to 🤔

**Comment by Enselic** [comment]
Hmm strange. Oh well, not much more to do now I suppose. I think we'll figure it out over time. Thank you for the investigation.

**Comment by boyvanduuren** [comment]
When I have some time I'll try to find an explanation, I'm curious what's causing the other test to pass.

**Comment by Enselic** [comment]
I hope you don't mind me closing this for now? I like when the PR inbox is clean :) Of course feel free to reopen if you discover something!

**Pull request closed without merging**
