### PR TITLE
Updated bat config dir for MacOs to ~/.config/bat/

### PR DESCRIPTION
**Pull request by lavifb**
Removed directories crate and using dirs_rs
Changed bat config file and cache dir on MacOs:
config: ~/.config/bat/config
cache: ~/.config/bat/cache/

### CODE REVIEW

**Comment by lavifb** [comment]
Fix for https://github.com/sharkdp/bat/issues/442

**Comment by lavifb** [comment]
I changed cache_dir on MacOS to ~/.cache/bat/ to agree with Linux

**Comment by sharkdp** [comment]
Thank you very much for working on this!

You are right, it seems like `directories` it not really actively maintained anymore :disappointed:. Still, it would be great if this could be handled in an external crate.

If there is no such crate, I'm fine with a temporary solution like you suggested here. However, it seems to me that this solution here is not quite sufficient, as we probably don't want to hard-code a specific directory, but rather add support for the `$XDG_CONFIG_HOME` and `$XDG_CACHE_HOME` environment variables (and only fall back to the hard-coded paths).

**Comment by lavifb** [comment]
Ah, you're right. I'll modify it to fallback to the XDG env variables first.

**Comment by sharkdp** [comment]
Looks great! I made a few small changes, hope that's fine.

**Comment by lavifb** [comment]
Yeah, of course! I didn't realize you could the `?` operator on `Option`s like you can for `Result`s.

**Comment by lavifb** [comment]
Out of curiosity, why did you have both `cache-dir` and `config-dir` flags for `bat cache`?

**Comment by sharkdp** [comment]
`--config-dir` was there for convenience to look up the configuration directory on any operating system. I use it in the `bat` README to make the documentation OS-independent.

I now added `--cache-dir` for completeness and for debugging purposes. I think it makes sense to let users also look up the caching directory via `bat cache --cache-dir`. Do you see any harm in adding `--cache-dir`?

**Comment by lavifb** [comment]
I agree it makes sense but it may be confusing to someone just reading the man page/help. So if you are trying to add a theme like in the README you use `bat cache --config-dir` and later call `bat cache --init`. With the option to accidentally call `bat cache --cache-dir`, I feel like there is room for a lot of confusion, similar to https://github.com/sharkdp/bat/issues/496. Mostly, since it is a flag for `bat cache` it is hard to tell if `config-dir` is the config for `bat` or `bat cache` or both and whether there is a difference between that and `cache-dir`.

It would possibly make more sense for these to be options for `bat`, so that now it feels like you are changing the config by modifying `bat --config-dir` and then caching the results with `bat cache`. This way it's clearer that `config-dir` and `cache-dir` are both for `bat` and `bat cache` is just there to compile the changes in `config-dir` into `cache-dir`.

**Comment by lavifb** [comment]
Now that I'm looking at it, it also may be clearer to use something like `bat cache --build` instead of `bat cache --init` because `init` feels like something that should only be called once but if I understand this correctly, you should call it anytime you want to add theme/syntax to the config. What do you think?

**Comment by sharkdp** [comment]
@lavifb Excellent points, yes. Completely agreed. I'll try to address this in another PR soon.

**Comment by lavifb** [comment]
Thanks! and thanks for making bat!

**Pull request merged**
