### PR TITLE
Apply some `clippy::pedantic` suggestions

### PR DESCRIPTION
**Pull request by acuteenvy**
Mostly readability improvements.

- [Inlined variables in `format!` strings](https://rust-lang.github.io/rust-clippy/master/index.html#/uninlined_format_args)
- [`map_or_else()` instead of `map().unwrap_or_else()`](https://rust-lang.github.io/rust-clippy/master/index.html#/map_unwrap_or)
- [Semicolons after expressions that return `()`](https://rust-lang.github.io/rust-clippy/master/index.html#/semicolon_if_nothing_returned)
- [`copied()` instead of `cloned()`](https://rust-lang.github.io/rust-clippy/master/index.html#/cloned_instead_of_copied)
- [`String::new()` instead of `"".to_string()`](https://rust-lang.github.io/rust-clippy/master/index.html#/manual_string_new)
- [Fixed `inneficient_to_string`](https://rust-lang.github.io/rust-clippy/master/index.html#/manual_string_new)
- [Removed `_` in patterns of type `()`](https://rust-lang.github.io/rust-clippy/master/index.html#/ignored_unit_patterns)

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you. Let's merge #2755 (and possibly others) first in order not to create too many conflicts.

**Comment by sharkdp** [comment]
#2755 has been merged now.

**Comment by Enselic** [comment]
It might sound silly, but can you split this out into a separate PR with simple-to-review and uncontroversial changes please? Right now the PR is too big for my taste.

**Comment by acuteenvy** [comment]
Sure, each clippy lint in a separate PR?

**Comment by Enselic** [comment]
The smaller the better as far as I'm concerned (but not too small of course)

**Comment by sharkdp** [comment]
Let's close this for now.

**Pull request closed without merging**
