### PR TITLE
Added Makefile to syntax tests

### PR DESCRIPTION
**Pull request by MattMattV**
Added a "complex Makefile" as described here : https://www.gnu.org/software/make/manual/html_node/Complex-Makefile.html

It should cover most of Makefile syntax !

### CODE REVIEW

**Comment by sharkdp** [comment]
@MattMattV Thank you very much for your contribution.

It would be great if we could find a Makefile that does not have a copyleft LICENSE attached to it. It's probably fine if we just add this one document, but I'm not really sure what that means for `bat` as a whole (do we "depend" on a GPL resource?).

I should have probably added this in the instructions in #1213, sorry!

**Comment by MattMattV** [comment]
Oh yes, sorry, I did not thought at all about this. I will find another one with another license.

**Comment by MattMattV** [comment]
I think this Makefile will be better, it's stating :

> Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

Which are included as asked in #1213 :slightly_smiling_face:

**Comment by sharkdp** [comment]
Thank you!

**Pull request merged**
