### PR TITLE
Target VimL upstream .sublime-syntax file

### PR DESCRIPTION
**Pull request by esensar**
Upstream **VimL Syntax** has been updated
to include `.sublime-syntax` file instead of `.tmLanguage`,
therefore manually added `.sublime-syntax` is no longer needed

### CODE REVIEW

**Comment by esensar** [comment]
Upstream has been updated to include `.sublime-syntax` directly: https://github.com/SalGnt/Sublime-VimL/pull/13

**Comment by sharkdp** [comment]
Thank you very much!

Could you please remove the `.bin` changes from the PR? I will manually update the binaries when I create the new release. The CI toolchain will test the new syntaxes anyways.

**Comment by esensar** [comment]
I was not sure if these should be committed or not. I will remove them.

**Comment by sharkdp** [comment]
Thank you very much!

**Pull request merged**
