### PR TITLE
Add support for Zig

### PR DESCRIPTION
**Pull request by paulsmith**
Adds syntax support for source code for the [Zig](https://ziglang.org/) programming language. 

image

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you very much for your contribution!

I added [the instructions for adding syntax tests](https://github.com/sharkdp/bat/blob/master/doc/assets.md#syntax-tests) just today, and I did forget that there are a few more steps involved when creating syntax tests for a new syntax. You actually first need a version of `bat` that has the new Zig syntax builtin. This means that you have to run `bash assets/create.sh` and then recompile `bat`. I will update the tests for you.

**Comment by moderation** [comment]
@paulsmith Awesome to see Zig support land. However I just compiled from the main branch and Zig support not available. `bat -L | rg -i zig` doesn't return anything and 
```
bat -l zig ~/Downloads/hello.zig
[bat error]: unknown syntax: 'zig'
```
Does Zig support need to be enabled in some way? ~~Any chance it isn't working as I'm compiling with `musl` - `cargo build --release --verbose --target x86_64-unknown-linux-musl`~~. I've confirmed Zig support isn't working on MacOS and Linux aarch64 too.

**Comment by sharkdp** [comment]
@moderation Until we release the next version, you need to manually generate the new builtin syntax set:

- make sure that all submodules are checked out as well
- compile `bat`
- run `bash assets/create.sh`
- compile `bat` again.

**Comment by moderation** [comment]
@sharkdp that worked great. Thanks

**Comment by sharkdp** [comment]
Added in [bat v0.18](https://github.com/sharkdp/bat/releases/tag/v0.18.0).

**Pull request merged**
