### PR TITLE
feat: Optionally write to a buffer instead of stdout

### PR DESCRIPTION
**Pull request by Piturnah**
Following on from my comment in #956, this PR adds the ability to write output to a `std::fmt` buffer instead of stdout. It does this by changing the `handle` used by the printer to be a mutable reference to either one of `dyn fmt::Write` or `dyn io::Write`.

Included is also an added example to show that it works. I didn't add it to the `PrettyPrinter` but I can do if it seems like a good idea.

Anything else let me know!

### CODE REVIEW

**Review by keith-hall — APPROVED** [review]

**Comment by sharkdp** [comment]
Can we please run a simple benchmark (e.g. `bat large-plaintext-file.txt`) to make sure this doesn't lead to any regression.

**Comment by Piturnah** [comment]
| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `bat-main` | 797.0 ± 6.1 | 790.5 | 817.9 | 1.01 ± 0.01 |
| `bat-2618` | 792.9 ± 2.6 | 788.7 | 800.6 | 1.00 |

Both compiled in release mode, `bat-main` comes from 8676bbf97f2832ad2231e102ca9c9b7b72267fda (the commit this PR is based on)

5 warmup runs, 20 runs

Command used to generate the file:
`tr -dc "A-Za-z 0-9" < /dev/urandom | fold -w100|head -n 1000000 > large-plaintext-file.txt`

**Comment by sharkdp** [comment]
Thank you very much!

> `tr -dc "A-Za-z 0-9" < /dev/urandom | fold -w100|head -n 1000000 > large-plaintext-file.txt`

:heart:

**Comment by sharkdp** [comment]
I'm just rebasing to current master to see if the tests still pass.

**Pull request merged**
