### PR TITLE
1703: Introducing MapExtensionToUnknown MappingTarget

### LINKED ISSUE #1703: Why isn't this Tmux.sublime-syntax file working for me?
I wanted to add syntax highlighting for for .tmux.conf file, so I add this file to `bat/syntaxes/`

https://raw.githubusercontent.com/gerardroche/sublime-tmux/master/Tmux.sublime-syntax

I then `bat cache -b` and try viewing my `.tmux.conf` file, bit it is still plain with no syntax highlighting. Have I missed something or does this file not work with bat for some reason?

### PR DESCRIPTION
**Pull request by cbolgiano**
Resolves #1703

### CODE REVIEW

**Comment by cbolgiano** [comment]
Thank you for the guidance and patience. I look forward to giving this another shot.

**Comment by cbolgiano** [comment]
Not quite there yet. Will continue to investigate.

**Comment by cbolgiano** [comment]
That helps greatly. Thank you.

Going to take some time to better understand the code and attempt again this weekend.

**Comment by cbolgiano** [comment]
Pushed.

**Comment by cbolgiano** [comment]
I ran regression tests but not integration tests locally this pass. Need to resolve the single failing integration test.

**Comment by Enselic** [comment]
Thanks for the updates. Just wanted to let you know that I have noticed your review request. Might take a while before I find the time to do a detailed review, however.

I glanced it over, and on a high level it looks good. But I think we can polish the new if-case code some more. While waiting for review, feel free to fix the lint warnings that clippy (the Rust linter) finds. You can see the lints in the "Files changed" tab in the PR.

**Pull request merged**
