### PR TITLE
Relax syntax mapping rule restrictions to allow brace expansion

### PR DESCRIPTION
**Pull request by cyqsimon**
It turns out there is a valid reason for glob rules to contain `{` and `}`. So I relaxed the compile time restriction.

See https://globster.xyz/.

### CODE REVIEW

**Review by keith-hall — APPROVED** [review]

**Comment by Enselic** [comment]
Thank you for the fix! Would be great if you could add a regression test. Prefer a "real" test over a unit test.

**Comment by cyqsimon** [comment]
> Thank you for the fix! Would be great if you could add a regression test. Prefer a "real" test over a unit test.

Hmm do we need it? It's part of the build script so it just won't build if there's a regression somehow.

**Comment by Enselic** [comment]
I would not call it "needed", but I do think it would be good to have. For one, it would make it easy to understand what the fix does and why it is needed (I currently don't understand this). And if someone undo your change either accidentally or deliberately, CI will fail, it and will (again) be clear why the code needs to look the way it does.

**Comment by sharkdp** [comment]
Merging this, since we're discussing the tests in #2866

**Pull request merged**
