### PR TITLE
Added JSONC and aws credentials to the syntax mappings

### PR DESCRIPTION
**Pull request by mxaddict**
I'm not 100% sure this is where these should be added.

Let me know if I need to move them somewhere else.

### CODE REVIEW

**Comment by Enselic** [comment]
Thank you for the PR. Let's wait with merging this until after https://github.com/sharkdp/bat/pull/2755 has landed to avoid creating conflicts.

**Comment by mxaddict** [comment]
> Thank you for the PR. Let's wait with this PR until after #2755 has landed to avoid creating conflicts.

Thanks for the update, let me know when it's viable to get this added, I'll fix the branch/pr conflicts then 😄

**Comment by sharkdp** [comment]
#2755 is now merged

**Comment by mxaddict** [comment]
> #2755 is now merged

Does #2755 add support for jsonc files?

Or do I need to fix my merge?

**Comment by keith-hall** [comment]
I'm pretty sure no actual changes were made to what mappings are applied by default in that PR, and I see no mention of JSONC in the changes

**Comment by mxaddict** [comment]
Alright, I'll rebase this PR on new master branch

**Comment by mxaddict** [comment]
I've applied my changes to the new structure, not 100% sure that it's done correctly though, let me know if anything needs changing.

**Review by keith-hall — APPROVED** [review]

**Comment by akkadaya** [comment]
Shouldn't AWS `config` & `credentials` be parsed as TOML instead of INI?

**Comment by mxaddict** [comment]
> Shouldn't AWS `config` & `credentials` be parsed as TOML instead of INI?

I'm not sure, the official amazon docs that I looked at did not mention if it was toml formatted, but from the examples, it looks like simple INI format to me.

Granted, basic INI if I remember correctly is valid TOML as well.

**Comment by mxaddict** [comment]
> > Shouldn't AWS `config` & `credentials` be parsed as TOML instead of INI?
> 
> I'm not sure, the official amazon docs that I looked at did not mention if it was toml formatted, but from the examples, it looks like simple INI format to me.
> 
> Granted, basic INI if I remember correctly is valid TOML as well.

image

**Comment by keith-hall** [comment]
conclusion: INI is correct 👍️

**Pull request merged**
