### PR TITLE
Add cat alias detection to info.sh

### PR DESCRIPTION
**Pull request by eth-p**
This should help in diagnosing issues when people have `cat` aliased to `bat`.

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you for looking into this.

This does not detect aliases in `zsh` or `bash`. Only shell functions.

**Comment by eth-p** [comment]
Whoops. I thought I originally accounted for that when I wrote the previous version which this is based on. I'll work on a fix for that, sorry.

**Comment by eth-p** [comment]
Alias detection is now implemented. It tested it on bash, and I believe zsh acts similarly to bash.

**Comment by sharkdp** [comment]
Thank you. I can confirm that it works on `zsh`.

**Pull request merged**
