### PR TITLE
Bump assets/syntaxes/01_Packages from 759d6ee to 5f6d4cf

### PR DESCRIPTION
**Pull request by WhyNotHugo**
Commits: https://github.com/sublimehq/Packages/compare/759d6ee...5f6d4cf

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
Huh, hang on, this is not working as I expected. Even though 5f6d4cf003d29c3c2c8169441ac1f9de8035d387 is in that range, the changes in there are not applying as expected.

**Comment by WhyNotHugo** [comment]
Yeah, actually, I think I didn't run `bash assets/create.sh` with the right version and my testing is bogus.

**Comment by keith-hall** [comment]
Please note that upgrading the Packages repo is not possible at this time because our syntax highlighting library doesn't support it yet (see https://github.com/sharkdp/bat/issues/2358#issuecomment-1269733255). If you have some commits you wish to apply to `bat`, the only real option at the moment is to create a patch file in this repo I believe...

**Comment by Enselic** [comment]
Let's close this PR for now to keep the PR inbox clean.

**Pull request closed without merging**
