### PR TITLE
Add Vue syntax

### PR DESCRIPTION
**Pull request by chaaaaarlotte**

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you very much for your contribution.

This will not work out of the box, as there is no `.sublime-syntax` file in that repository.

Please see: https://github.com/sharkdp/bat/tree/master/assets#syntax-highlighting-in-bat

**Comment by chaaaaarlotte** [comment]
`.sublime-syntax` file is in `new` branch
https://github.com/vuejs/vue-syntax-highlight/tree/new

**Comment by sharkdp** [comment]
I missed that, thank you!

**Comment by sharkdp** [comment]
This has been released in [bat 0.13](https://github.com/sharkdp/bat/releases/tag/v0.13.0).

**Pull request merged**
