### PR TITLE
Added support for windows/ARM64

### LINKED ISSUE #2644: Windows ARM64 Build
Would it be possible to include a Windows ARM build in future releases? Apologies if I missed an existing request for this, I didn't see one when I searched the issues.

### PR DESCRIPTION
**Pull request by Raghav-Bell**
It fixes #2644

### CODE REVIEW

**Comment by Raghav-Bell** [comment]
Being `windows_ arm_64` a new platform, initial rust releases don't support Windows/ARM64. For more details check out [rustlang/rust#52659](https://github.com/rust-lang/rust/issues/52659), [rustlang/rust#53621](https://github.com/rust-lang/rust/pull/53621), and [rust-lang/rust/compiler/rustc_target/src/spec/mod.rs](https://github.com/rust-lang/rust/blob/master/compiler/rustc_target/src/spec/mod.rs).

**Comment by Enselic** [comment]
Thank you for the contribution! We're gonna need CI passing before we can merge this though.

**Comment by Raghav-Bell** [comment]
@Enselic  As this PR adds  `aarch64-pc-windows-msvc` target in CI (which is also the only failing target) is tier 2 target for `rust` (stated above) which doesn't guarantee all test passing. Please help me to resolve error.

**Comment by sharkdp** [comment]
There's probably no way we can execute the tests in GitHub CI, because we don't have a ARM64 virtual machine?

**Comment by Raghav-Bell** [comment]
@sharkdp As of now windows ARM64 runner is in prelease in github-actions runner version [2.309.0](https://github.com/actions/runner/tree/v2.309.0) but it is not production ready yet. I found similar issue for `ring` , check it out here : [Add support for aarch64-pc-windows-msvc#1614](https://github.com/briansmith/ring/issues/1614) . We can even try self hosted runner for it as state here [Actions: Self-hosted runners now support Windows ARM64](https://github.com/github/roadmap/issues/616).

**Comment by sharkdp** [comment]
> We can even try self hosted runner for it as stated here [Actions: Self-hosted runners now support Windows ARM64](https://github.com/github/roadmap/issues/616).

I would rather not do that. I want a stable CI system. Let's just disable the tests for this platform for now?

**Comment by Raghav-Bell** [comment]
@sharkdp I think they are already done (not all but most of).

https://github.com/sharkdp/bat/blob/e5c81ed41e5857dfbe7654451b32de9a674b877e/.github/workflows/CICD.yml#L239-L246

**Comment by Raghav-Bell** [comment]
I think this issue is due to wrong version of  MS Build Tools ( [https://github.com/tauri-apps/wry/issues/410](https://github.com/tauri-apps/wry/issues/410)), we can setup right version using `vs-version` ([setup-msbuild](https://github.com/microsoft/setup-msbuild)). Please let me know how can we resolve this.

**Comment by Enselic** [comment]
I don't think anyone knows how to resolve it.

Closing for now to keep the PR inbox clean. Of course feel free to re-open if you resume work on this!

**Pull request closed without merging**
