### PR TITLE
Implemented LLVM syntax highlighting and regression tests

### PR DESCRIPTION
**Pull request by ioncodes**
This PR implemented LLVM IR syntax highlighting as per #1777. Let me know if this change would be beneficial and I'll add it to the CHANGELOG.md!

### CODE REVIEW

**Comment by ioncodes** [comment]
Here's a screenshot of what it looks like: image

**Comment by keith-hall** [comment]
Hi, nice that you worked on a syntax definition for a language you are interested in and shared it here - thanks! :)

I have a question - did you consider maintaining it in a separate repository? The reason I ask is, if/when it becomes popular, I can foresee that we may see lots of issues about it or PRs relating to improving it, and it would be nice to be able to just bump a git submodule rather than have lots of noise in this repo

**Comment by ioncodes** [comment]
I could definitely do that! Would you like me to close this PR and make a new repo with the syntax file and then submit a PR with that submodule added to 02_Extras or just wait it out until it receives some traffic first?

**Comment by keith-hall** [comment]
Up to you :) It may make sense to wait and see what others think, but the good news is we've added some syntax definitions recently which don't meet the 10k package control requirement (i.e. https://github.com/sharkdp/bat/pull/1685#issuecomment-886187561), and we are working on performance improvements so that having a large number of syntaxes should be less of a problem. But I certainly think we're more likely to agree to add another submodule than a sublime-syntax directly :)

**Comment by vzaliva** [comment]
I am working with LLVM a lot and would like to be able to us this syntax highligting. How can I do this. I have bat version 0.18.2.
Can I install additional syntax locally?

**Comment by ioncodes** [comment]
@vzaliva 

The way I did it was:

1. Pull my commit (make sure to fetch all submodules)
2. `bash assets/create.sh`
3. `cargo install --path . --locked --force`

This creates a new syntax blob and compiled bat with it. It will also install bat (and overwrite your current one I'd assume) globally.

If that doesn't work let me know. If it's urgent you can reach out to me on [Twitter](https://twitter.com/layle_ctf).

**Pull request closed without merging**
