### PR TITLE
Explain how to fix no output issue

### PR DESCRIPTION
**Pull request by sorenbug**
I just ran into this so I figured it might be helpful for others.

I don't know what other details are really needed, so if something needs to be added, just let me know 👍

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you for your contribution!

If this is definitely required for the binaries on Windows, maybe we should add the hint in this section: https://github.com/sharkdp/bat#on-windows ?

**Comment by sorenbug** [comment]
Got it, will do

**Comment by sharkdp** [comment]
I was referring to the "installation / on Windows" section, which I think would be more suited

**Comment by sharkdp** [comment]
Sorry for being pedantic here, but: is this required when installing via `scoop`/`choco` as well?

Otherwise, please move it up to the part: "You can download prebuilt binaries from the [Release page](https://github.com/sharkdp/bat/releases) …" and maybe split that sentence into multiple paragraphs or subsections.

**Comment by sorenbug** [comment]
It is at least needed on `choco` as that's how I installed it. I would assume the same for scoop unless there's any additional dependencies in the scoop package that there's not in the choco package.

**Comment by sharkdp** [comment]
@rasmuskriest @meltinglava Can you confirm that this is needed for the Chocolatey and scoop packages, respectively?

**Comment by meltinglava** [comment]
What the scoop maintainers did was suggest `less` as a pager as seen in [bat.json](https://github.com/ScoopInstaller/Main/blob/9059ade74e6a4b5a78e7cdbeb7e45897f093e4c3/bucket/bat.json#L7). I have had no problems with bat once installing less, thow i am not using much windows any more.

**Comment by rasmuskriest** [comment]
I am going to add a dependency for [vcredist140](https://chocolatey.org/packages/vcredist140) to the Chocolatey package so that this manual step will not be necessary in this case (similar to `less`).

**Comment by sharkdp** [comment]
@meltinglava I think this is independent from whether or not `less` is added as a dependency. The question is if users need the "Microsoft Visual C++ Redistributable"  package to be installed. I would guess so, if this is also the case for the manual install and the Chocolatey package.

@rasmuskriest Great! Thank you very much!

**Pull request merged**
