### PR TITLE
Add Jinja2 syntax

### PR DESCRIPTION
**Pull request by Martin819**
Add sublime-syntax file for a Jinja2

Example:
Screenshot from 2019-09-03 16-24-17

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you for your contribution!

Where does this file come from? If you did not create it yourself, we have to add an acknowledgement / LICENSE.

This is one of the reasons why we normally add new syntaxes via submodules, see https://github.com/sharkdp/bat/blob/master/assets/README.md (step 1). This also helps us when updating the syntax in the future.

**Comment by Martin819** [comment]
Hi @sharkdp, the original file is from https://github.com/kudago/jinja2-tmbundle/blob/master/Syntaxes/Jinja2.tmLanguage which is to be installed as a package for a sublime text. I have converted the file to sublime-syntax and made some alterations so it's only based on this file, but not the same file. The need for converting the file is also a reason, why I haven't added it as a submodule.

**Comment by sharkdp** [comment]
Thank you for the explanation.

In this case, please add it as a submodule anyway and shortly document the manual changes in the appropriate section in https://github.com/sharkdp/bat/blob/master/assets/README.md

**Comment by Martin819** [comment]
@sharkdp  I have included forked repo with files already converted to sublime-syntax as a submodule.

**Comment by sharkdp** [comment]
Thank you!

**Comment by sharkdp** [comment]
This has been released in [bat 0.13](https://github.com/sharkdp/bat/releases/tag/v0.13.0).

**Pull request merged**
