### PR TITLE
Added a JavaScript test file

### PR DESCRIPTION
**Pull request by DanielVip3**
I made this file which is just a random bunch of (funny) things, but I tried to add everything possible inside it.

Bat highlights it correctly, and in such an enjoyable way.

Refers to #1213.

### CODE REVIEW

**Comment by DanielVip3** [comment]
The second test failed (Test with new syntaxes and themes) but I didn't understand what this test was about and it looks like it doesn't depend from my file but from other's files?

**Comment by sharkdp** [comment]
Thank you very much for your contribution!

> The second test failed (Test with new syntaxes and themes) but I didn't understand what this test was about and it looks like it doesn't depend from my file but from other's files?

Please make sure that you are running `bat` 0.16.

**Comment by DanielVip3** [comment]
I think I already was
image

**Comment by DanielVip3** [comment]
I noticed #1254 and I was running on Windows, so I updated my local branch and re-executed the script.
Now all those tests should pass.

**Comment by henil** [comment]
Please only include the files you are changing. You have deleted many other files.

**Comment by DanielVip3** [comment]
Okay, gonna close this and open another PR again with a new fork.

**Pull request closed without merging**
