### PR TITLE
Add padding above headers when no grid

### LINKED ISSUE #968: Extra [vertical] padding around headers when no grid
I like to have `BAT_STYLE=header,numbers,changes`, but when showing multiple files only having a single line header with the file name doesn't visually separate files very well… It would be nice to have the option of a blank line above and/or below the header. Perhaps also an optional blank line instead of `---8<---` with the `snip` option…

### PR DESCRIPTION
**Pull request by pt2121**
closes #968

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you for your contribution!

I would definitely prefer a version which would not add the blank line before the first file.

**Comment by pt2121** [comment]
Gotcha. I will update my PR. Thanks for the feedback.

**Comment by sharkdp** [comment]
Thank you for the updates. Note that we only want to show the padding if the `header` style component is enabled. We do not want to add padding otherwise.

**Comment by pt2121** [comment]
Thanks again for quick responses. 👍

**Pull request merged**
