### PR TITLE
Add libmagic extension guessing

### PR DESCRIPTION
**Pull request by hingev**
There was a suggestion in #1545 to use libmagic to guess file types.

Co-authored-by: In-line <inline0@protonmail.com>

### CODE REVIEW

**Comment by Enselic** [comment]
Thanks for taking the time to make a contribution, but did you see [this comment](https://github.com/sharkdp/bat/issues/1545#issuecomment-782604457) where @sharkdp says he does not think libmagic is a good fit for bat?

**Comment by hingev** [comment]
Yes, that's why it is packaged as an optional feature

**Comment by Enselic** [comment]
I’ll let @sharkdp have the final say in this PR, but would still like to ask: In what way does making it an optional feature make it a better fit for bat?

**Comment by hingev** [comment]
I was looking at open feature-request issues, and came around #1545 
Since @sharkdp does not want libmagic, the official builds can still be compiled without it, while other people who need it can compile with the feature enabled.

**Comment by sharkdp** [comment]
@hingev Thank you very much for your contribution. I'd rather not include this in `bat`, and focus on #1600. Even if this is included as an optional feature (I appreciate the effort), we will have to maintain this code in the future, if we merge this PR. Unless someone can demonstrate that this would have significant advantages over #1600, I'd rather not merge this.

**Pull request closed without merging**
