### PR TITLE
Add Racket syntax

### LINKED ISSUE #1884: Syntax highlighting for Racket
**Syntax:**
[Racket](https://racket-lang.org/)

**Guideline Criteria:**
[packagecontro.io/packages/Racket](https://packagecontrol.io/packages/Racket)

### PR DESCRIPTION
**Pull request by jubnzv**
Add syntax files for Racket language.

It is based on [Racket](https://packagecontrol.io/packages/Racket) syntax highlighting plugin, which have more than 10K downloads at packagecontrol.

For the test, I used [some old MIT-licensed code](https://github.com/jubnzv/nix.rkt/blob/master/nix/test.rkt) written by me.

Closes #1884

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you very much for your contribution!

I think the output file for the syntax highlighting tests is missing?

**Comment by jubnzv** [comment]
@sharkdp Oops, I added the missing file.

**Review by sharkdp — APPROVED** [review]
@Enselic should we wait with adding new syntaxes while your syntax loading improvements are still in progress?

**Comment by Enselic** [comment]
@sharkdp Nope, no need to wait, so please go ahead.

(I never (deliberately) merge anything that blocks others or blocks us from making a release)

**Pull request merged**
