### PR TITLE
Add note regarding options passed to less by default in manpage 

### LINKED ISSUE #1913: Bat displays escape codes when run with sudo and less -X or -F
**Describe the bug you encountered:**

```sh
❯ sudo bat .
[bat error]: '.' is a directory.
❯ sudo bat . --pager=less
[bat error]: '.' is a directory.
❯ sudo bat . --pager='less -F'
ESC[31m[bat error]ESC[0m: '.' is a directory.
❯ bat . --pager=less
[bat error]: '.' is a directory.
❯ bat . --pager='less -F'
[bat error]: '.' is a directory.
❯ bat .
[bat error]: '.' is a directory.
❯ sudo bat . --pager='less -X'
ESC[31m[bat error]ESC[0m: '.' is a directory.
```
image

**What did you expect to happen instead?**

Adding options to the pager does not break coloring.

**How did you install `bat`?**

Arch

---

**bat version and environment**

#### Software version

bat 0.18.3 (b146958)

#### Operating system

Linux 5.14.9-arch2-1

#### Command-line

```bash
bat . '--pager=less -F' --diagnostic 
```

#### Environment variables

```bash
SHELL=/bin/zsh
PAGER=less
LESS=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### Config file

Could not read contents of '/root/.config/bat/config': No such file or directory (os error 2).

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version 
less 590 (PCRE2 regular expressions)
Copyright (C) 1984-2021  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

### PR DESCRIPTION
**Pull request by mdibaiee**
Fixes #1913

Signed-off-by: Mahdi Dibaiee <mdibaiee@pm.me>

### CODE REVIEW

**Review by Enselic — CHANGES_REQUESTED** [review]
Thanks for taking the time to make a contribution, but I think you missed the paragraph 4 paragraphs down that also talks about `--RAW-CONTROL-CHARS`?

**Comment by mdibaiee** [comment]
@Enselic ah, you are right, then I guess the original issue #1913 can be closed as this is already documented?

**Comment by Enselic** [comment]
The issue talks about the man page. I suspect we don't mention it in the man page. Maybe we should?

**Comment by mdibaiee** [comment]
@Enselic oh I see, that's my misunderstanding then. I'll see if I can add it to the manpage 👍

**Comment by sharkdp** [comment]
@mdibaiee Thank you very much. Did you verify that this "renders" correctly in `man` by building `bat` and checking the resulting `bat.1` file via `bat -l bat.1`?

**Comment by mdibaiee** [comment]
Yes, this is the resulting manpage section:

```
man target/debug/build/bat-62ebb303f306a280/out/assets/manual/bat.1
```
```
       --pager <command>

              Determine which pager is used. This option will override the PAGER and BAT_PAGER environment variables. The default pager is 'less'. To control when the pager is used,
              see the '--paging' option. Example: '--pager "less -RF"'.

              Note: By default, if the pager is set to 'less' (and no command-line options are specified), versions older than 530.  The '-R' option is needed to interpret ANSI col-
              ors  correctly.  The  second option ('-F') instructs less to exit immediately if the output size is smaller than the vertical size of the terminal.  This is convenient
              for small files because you do not have to press 'q' to quit the pager. The third option ('-X') is needed to fix a bug with the '--quit-if-one-screen' feature  in  old
              versions of 'less'. Unfortunately, it also breaks mouse-wheel support in 'less'.  If you want to enable mouse-wheel scrolling on older versions of 'less', you can pass
              just '-R' (as in the example above, this will disable the quit-if-one-screen feature). For less 530 or newer, it should work out of the box.
```

image

**Comment by mdibaiee** [comment]
Okay now it's rendering correctly:

```
              Determine which pager is used. This option will override the PAGER and BAT_PAGER environment variables. The default pager is 'less'. To control when the pager is used,
              see the '--paging' option. Example: '--pager "less -RF"'.

              Note: By default, if the pager is set to 'less' (and no command-line options are specified), 'bat'  will  pass  the  following  command  line  options  to  the  pager:
              '-R'/'--RAW-CONTROL-CHARS',  '-F'/'--quit-if-one-screen'  and '-X'/'--no-init'. The last option ('-X') is only used for 'less' versions older than 530. The '-R' option
              is needed to interpret ANSI colors correctly. The second option ('-F') instructs less to exit immediately if the output size is smaller than the vertical size  of  the
              terminal.  This  is convenient for small files because you do not have to press 'q' to quit the pager. The third option ('-X') is needed to fix a bug with the '--quit-
              if-one-screen' feature in old versions of 'less'. Unfortunately, it also breaks mouse-wheel support in 'less'. If you want to enable  mouse-wheel  scrolling  on  older
              versions  of  'less',  you can pass just '-R' (as in the example above, this will disable the quit-if-one-screen feature). For less 530 or newer, it should work out of
              the box.
```

image

**Review by sharkdp — APPROVED** [review]
Thank you!

**Review by Enselic — APPROVED** [review]
Am out in the forest so my abilities are limited, but it looks good to me

**Pull request merged**
