### PR TITLE
Simplify issue templates

### PR DESCRIPTION
**Pull request by sharkdp**
Just a few small things that I thought about after looking how the new templates look like on GitHub.

The main change is that I made the "header" section into a HTML comment. This way, users will not have to remove the header part.

@eth-p What do you think?

### CODE REVIEW

**Comment by sharkdp** [comment]
Also, I wonder if we should add a "Question" template or rename "Bug report" to "Bug report or question". A lot of opened issues actually fall into this category.

Maybe we could also add a very simple (empty?) template for "Feature request".

**Comment by eth-p** [comment]
> The main change is that I made the "header" section into a HTML comment. This way, users will not have to remove the header part.

I actually forgot that was an option. Not to mention: that's a perfect use for comments, too.

> Also, I wonder if we should add a "Question" template or rename "Bug report" to "Bug report or question". A lot of opened issues actually fall into this category.

True... I think the former would be the best way to tailor the templates. I suspect that no matter which one we choose though, we're going to need to manually change the labels on issues at done point (e.g. a question turns out to be a bug, or a bug turns out bring a question).

> Maybe we could also add a very simple (empty?) template for "Feature request".

After looking at the UI for issues when templates are enabled, I absolutely agree. The blank template option isn't as clearly displayed as the others, and it would make it easier for somebody if they didn't notice it.

**Comment by sharkdp** [comment]
> True... I think the former would be the best way to tailor the templates

Agreed. I added two new templates. 

Thank you very much for starting this. Excited to see how this works out. I'm pretty sure it will save us a lot of work!

**Comment by eth-p** [comment]
> I'm pretty sure it will save us a lot of work!

Hopefully! With the `info.sh` script, it should also help reduce the back-and-forth required to diagnose the cause behind some issues.

**Pull request merged**
